### PR TITLE
Feat gh actions

### PR DESCRIPTION
**Pull request by jmccreight**
@scrasmussen

### CODE REVIEW

**Comment by jmccreight** [comment]
this includes #230

**Comment by scrasmussen** [comment]
Thanks for this PR @jmccreight ! Sorry, I had somehow missed this and didn't see it until yesterday. I am spending some time right now trying to see what is causing the builds (other than the standard install) to fail, trying to see how difficult it will be to get them all working.

**Comment by scrasmussen** [comment]
@jmccreight Just a quick update, I've made a [branch with updates](https://github.com/scrasmussen/wrf_hydro_py/tree/pr238-ci-fixes) to this pr. Dependencies updates and changes to fix failing CI tests. Currently there is [only one test](https://github.com/scrasmussen/wrf_hydro_py/actions/runs/5114818979/jobs/9195451137#step:7:1171) that is failing but it is a bit more difficult to fix than the others. I'll continue to work on it and then it looks like the Ubuntu and MacOS tests will all pass. Would you prefer me to merge those fixes into your `feat_gh_actions` branch so the CI tests are passing or merge your branch and then create new PR with my fixes?

**Review by scrasmussen — APPROVED** [review]

**Comment by jmccreight** [comment]
Sorry, I was on vacation last week. It's totally up to you! I am no
benevolent dictator for life on this! I think I would have done as you did.
What is the test that's problematic? Maybe I have some idea if it's still
plaguing you



-------------------------------------------------------
James L. McCreight
Research Hydrologist ~ Software Engineer
USGS Enterprise Capacity
UCAR CPAESS
cell:         831-261-5149

**Comment by scrasmussen** [comment]
@jmccreight No worries, hope you enjoyed your vacation! And are willing to accept a new role as "benevolent advisor" ; ) 

The failing Ubuntu test is [test_ens_compose_restore](https://github.com/scrasmussen/wrf_hydro_py/blob/5848e6a94cdc0d471fe306e1f95153581fe9eace/wrfhydropy/tests/test_ensemble.py#L149). I was able to get it to pass by adding [this if statement](https://github.com/scrasmussen/wrf_hydro_py/blob/5848e6a94cdc0d471fe306e1f95153581fe9eace/wrfhydropy/core/outputdiffs.py#L439-L443) which checks differences in the unexpected_diffs from deepdiff. The only difference is the `_compose_dir`, which seems like an ok thing to just have a warning about, but I'm not sure. 

If the `_compose_dir` difference is ok for just the test case but we want it to fail otherwise, I can edit the `test_ens_compose_restore` function so it does that.


The failing test message:
```
FAILED test_ensemble.py::test_ens_compose_restore - ValueError: ('Unexpected attribute
differences in unexpected members from DeepDiff output:', "root['_compose_dir']", ':', 
'/tmp/pytest-of-runner/pytest-0/test_ens_compose_restore0/ensemble_memory/member_000', ' 
!= ', '/tmp/pytest-of-runner/pytest-0/test_ens_compose_restore0/ensemble_memory
/member_001')
```

**Pull request merged**
