### PR TITLE
Simulation methods for stashing and restoring model, domain, output s…

### PR DESCRIPTION
**Pull request by jmccreight**
…ub-objects

### CODE REVIEW

**Comment by jmccreight** [comment]
Bunch-o-pep8 stuff in there, but the main idea is in the big green block.

**Comment by jmccreight** [comment]
I do not get that failure.

**Comment by jmccreight** [comment]
I see it now... must have been an editing blunder...

**Comment by jmccreight** [comment]
I fell behind in the branch I was making those changes on, then I dropped the file in wholesale without updating.... my bad. Should be fixed. Thx, GOD, for testing!

**Comment by jmills-ncar** [comment]
Thanks for the pep8 cleanup

**Pull request merged**
