### PR TITLE
Model time dot file

### PR DESCRIPTION
**Pull request by jmccreight**

### CODE REVIEW

**Comment by jmccreight** [comment]
This is the more complete deal around writing the model times to dot files. It includes a function to read them and some polish on when they are created.

**Comment by jmccreight** [comment]
NO tests.

**Comment by jmills-ncar** [comment]
Is this functionality for performance reasons around pickling in ensembles?

**Comment by jmccreight** [comment]
It's related. It's a mechanism for tracking the model time. Getting the model time through a glob of restart files becomes horrible inefficient was the number of restart files increases (the old method). Opening the pickle files is an alternative method. But I dont really like to have to do that when I'm not using wrfhydropy per se. I need to know the model time and that it's the same for all members before invoking DART. This is perty clean with super minimal overhead. Can also be used to tell if a run was successful.

**Pull request merged**
